apiVersion: argoproj.io/v1alpha1 
kind: Application
metadata:
  name: cv-ranker-capstone
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ducanh88k7/k8s-manifests.git
    targetRevision: main
    path: cv-ranker-chart
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false

# "Argo CD phải deploy cái gì, từ đâu, vào đâu?"